import 'package:cloud_firestore/cloud_firestore.dart';

// UserModel defines the structure of a user in our app.
// Every user (Student, Landlord) is stored in the
// 'users' collection in Firestore using this structure.
class UserModel {
  // ── Basic fields every user has ──
  final String uid;          // Unique ID generated by Firebase Auth
  final String name;         // Full name of the user
  final String email;        // Email address used to login
  final String phone;        // Phone number
  final String role;         // 'student' or 'landlord'
  final String profileImage; // URL of profile photo stored in Firebase Storage
  final DateTime createdAt;  // When the account was created

  // ── Student-only fields ──
  final String university;          // University the student attends
                                    // e.g. 'SLTC Research University'
                                    // Used to show nearby boarding listings
  final List<String> savedListings; // IDs of listings the student saved/favourited
  final List<String> bookings;      // IDs of bookings the student made

  // ── Landlord-only fields ──
  final List<String> listings; // IDs of listings the landlord posted
  final bool verified;         // Whether the landlord is verified by admin

  // Constructor - creates a UserModel object with all required fields
  UserModel({
    required this.uid,
    required this.name,
    required this.email,
    required this.phone,
    required this.role,
    this.profileImage = '',   // Default empty string if no photo
    required this.createdAt,
    this.university = '',     // Default empty string for landlords
    this.savedListings = const [], // Default empty list for students
    this.bookings = const [],      // Default empty list for students
    this.listings = const [],      // Default empty list for landlords
    this.verified = false,         // Default unverified for landlords
  });

  // ── fromFirestore ──
  // Converts raw Firestore data (a map) into a UserModel object.
  // Called when we READ data FROM Firebase.
  factory UserModel.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;

    return UserModel(
      uid: data['uid'] ?? '',
      name: data['name'] ?? '',
      email: data['email'] ?? '',
      phone: data['phone'] ?? '',
      role: data['role'] ?? 'student',
      profileImage: data['profileImage'] ?? '',
      createdAt: (data['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
      university: data['university'] ?? '',   // Read university from Firestore
      savedListings: List<String>.from(data['savedListings'] ?? []),
      bookings: List<String>.from(data['bookings'] ?? []),
      listings: List<String>.from(data['listings'] ?? []),
      verified: data['verified'] ?? false,
    );
  }

  // ── toFirestore ──
  // Converts this UserModel object into a Map that Firestore can save.
  // Called when we WRITE data TO Firebase.
  Map<String, dynamic> toFirestore() {
    return {
      'uid': uid,
      'name': name,
      'email': email,
      'phone': phone,
      'role': role,
      'profileImage': profileImage,
      'createdAt': Timestamp.fromDate(createdAt),
      'university': university,   // Save university to Firestore
      'savedListings': savedListings,
      'bookings': bookings,
      'listings': listings,
      'verified': verified,
    };
  }

  // ── copyWith ──
  // Creates a copy of this user with some fields changed.
  // Useful when updating just one field without changing others.
  // Example: userModel.copyWith(name: 'New Name')
  UserModel copyWith({
    String? uid,
    String? name,
    String? email,
    String? phone,
    String? role,
    String? profileImage,
    DateTime? createdAt,
    String? university,
    List<String>? savedListings,
    List<String>? bookings,
    List<String>? listings,
    bool? verified,
  }) {
    return UserModel(
      uid: uid ?? this.uid,
      name: name ?? this.name,
      email: email ?? this.email,
      phone: phone ?? this.phone,
      role: role ?? this.role,
      profileImage: profileImage ?? this.profileImage,
      createdAt: createdAt ?? this.createdAt,
      university: university ?? this.university,
      savedListings: savedListings ?? this.savedListings,
      bookings: bookings ?? this.bookings,
      listings: listings ?? this.listings,
      verified: verified ?? this.verified,
    );
  }

  // ── Helper getters ──
  // Quick way to check what role this user has
  bool get isStudent => role == 'student';
  bool get isLandlord => role == 'landlord';
}